### ISSUE TITLE
Wrong dataset link

### ISSUE THREAD

**Issue by BianchiGiulia** [MkButterfingers/Neural_Networks_Extremism_NLP_Arabic#1]
Hi!
Thank you so much for publishing this dataset, I'd like to read more about it but the link in the file [dataset.txt](https://github.com/MkButterfingers/Neural_Networks_Extremism_NLP_Arabic/blob/main/dataset.txt), seems to be wrong. Could you post the right one or some form of documentation of the data?

Thank you,
Giulia

**Comment by Mohamed-KS** [comment]
Hello,

Thank you for reaching out. The data set is in the allData.csv file. If you want to know more about it, check out this link that I got it from https://ieee-dataport.org/documents/annotated-arabic-extremism-tweets#files

If you have any questions feel free to contact me.

Thank you,
Mohamed

Sent from Outlook for Android<https://aka.ms/AAb9ysg>
________________________________
From: Giulia Bianchi ***@***.***>
Sent: Tuesday, August 27, 2024 1:37:09 PM
To: MkButterfingers/Neural_Networks_Extremism_NLP_Arabic ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [MkButterfingers/Neural_Networks_Extremism_NLP_Arabic] Wrong dataset link (Issue #1)


Hi!
Thank you so much for publishing this dataset, I'd like to read more about it but the link in the file dataset.txt<https://github.com/MkButterfingers/Neural_Networks_Extremism_NLP_Arabic/blob/main/dataset.txt>, seems to be wrong. Could you post the right one or some form of documentation of the data?

Thank you,
Giulia

**Comment by BianchiGiulia** [comment]
Thank you for the prompt reply!
